name: Build, Publish, and Release .NET App

on:
  push:
    tags:
      - 'v*'  # Trigger the action when you push a tag (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the application as a single file (self-contained)
        run: dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true -o ./publish

      - name: Archive published files
        run: tar -czvf publish.tar.gz ./publish

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: publish.tar.gz

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
